AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-capasity-decreaser

  Sample SAM Template for serverless-capasity-decreaser

Parameters:
  NotificationReceiverAddress:
    Type: String
  StatusCheckInterval:
    Type: Number
    Default: 600
  StateMachineTimeout:
    Type: Number
    Default: 7200
Resources:
  #---------------------------------------------
  #---- Transfer Machine
  #---------------------------------------------
  ServerlessDecreaser:
    Type: AWS::Serverless::StateMachine 
    Properties:
      DefinitionUri: statemachine/decreaser.asl.json
      DefinitionSubstitutions:
        SnsTopicArn: !Ref Topic
        StatusCheckInterval: !Ref StatusCheckInterval
        StateMachineTimeout: !Ref StateMachineTimeout
      Role: !GetAtt DecreaserMachineRole.Arn
      Events:
        CompleteEvent:
          Type: EventBridgeRule 
          Properties:
            Target:
              Id: complete-receive-machine
            Pattern:
              source:
                - "aws.rds"
              detail-type:
                - "RDS DB Cluster Event"
              detail:
                EventID: 
                 - "RDS-EVENT-0170"
  DecreaserMachineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: "serverless-decreaser-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - rds:ModifyDBCluster
                  - rds:DescribeDBClusters
                  - rds:DescribeDBInstances
                Resource:
                  - '*'
              - Effect: Allow
                Action: 
                  - sns:Publish
                Resource:
                  - !Ref Topic
  Topic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: serverless-decreaser-topic
      DisplayName: serverless-decreaser-topic
  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref Topic
      Protocol: email
      Endpoint: !Ref NotificationReceiverAddress